# Generated by Django 4.0.4 on 2022-05-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_auto_20220507_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
    ]
